#!/usr/bin/env node
/**
 * Generate src/lib/contract.gen.ts from apps/api/schema/contract.json.
 *
 * The contract JSON is exported from the Pydantic models by
 * `apps/api/scripts/export_schema.py`. Property names are converted from
 * snake_case (wire format) to camelCase, because the app speaks camelCase
 * internally and `lib/api/client.ts` is the single snake/camel boundary.
 *
 * Emitter rules (small, dependency-free JSON-Schema subset):
 *   - object defs with `properties`  → `export interface`
 *   - `enum`                         → string-literal unions
 *   - `anyOf`                        → unions; `null` is dropped for OPTIONAL
 *     properties (they are emitted with `?`, matching app conventions) and
 *     kept for required nullable properties
 *   - `additionalProperties` objects → `Record<string, T>`
 *   - properties not in `required`   → optional (`?`)
 *
 * Run via: npm run gen:types
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CONTRACT_PATH = path.resolve(__dirname, "../../api/schema/contract.json");
const OUT_PATH = path.resolve(__dirname, "../src/lib/contract.gen.ts");

const toCamel = (s) => s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());

/** Convert a JSON-Schema node to a TS type expression. */
function tsType(schema, { dropNull = false } = {}) {
  if (!schema || typeof schema !== "object") return "unknown";
  if (schema.$ref) {
    const name = schema.$ref.split("/").pop();
    if (!name) throw new Error(`bad $ref: ${schema.$ref}`);
    return name;
  }
  if (Array.isArray(schema.enum)) {
    return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  }
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (Array.isArray(schema.anyOf)) {
    const parts = schema.anyOf
      .filter((s) => !(dropNull && s && s.type === "null"))
      .map((s) => tsType(s));
    const uniq = [...new Set(parts)];
    return uniq.length > 0 ? uniq.join(" | ") : "null";
  }
  switch (schema.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return `Array<${tsType(schema.items ?? {})}>`;
    case "object":
      if (schema.additionalProperties && typeof schema.additionalProperties === "object") {
        return `Record<string, ${tsType(schema.additionalProperties)}>`;
      }
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

/** Emit one named definition. */
function emitDef(name, schema) {
  const lines = [];
  if (schema.description) lines.push(`/** ${schema.description} */`);
  if (schema.type === "object" && schema.properties) {
    const required = new Set(schema.required ?? []);
    lines.push(`export interface ${name} {`);
    for (const [prop, propSchema] of Object.entries(schema.properties)) {
      const optional = !required.has(prop);
      const type = tsType(propSchema, { dropNull: optional });
      if (propSchema.description) lines.push(`  /** ${propSchema.description} */`);
      lines.push(`  ${toCamel(prop)}${optional ? "?" : ""}: ${type};`);
    }
    lines.push("}");
  } else {
    lines.push(`export type ${name} = ${tsType(schema)};`);
  }
  return lines.join("\n");
}

function main() {
  const contract = JSON.parse(readFileSync(CONTRACT_PATH, "utf8"));
  const defs = contract.$defs ?? {};

  const blocks = Object.entries(defs).map(([name, schema]) => emitDef(name, schema));

  const out = [
    "// AUTO-GENERATED by scripts/gen-types.mjs — DO NOT EDIT.",
    "// Source of truth: apps/api/contexthub/models.py",
    "//   1. cd apps/api && python scripts/export_schema.py",
    "//   2. cd apps/desktop && npm run gen:types",
    "// Property names are camelCase; lib/api/client.ts converts to/from the",
    "// snake_case wire format at the HTTP boundary.",
    "",
    `export const CONTRACT_VERSION = ${JSON.stringify(contract.contract_version)};`,
    "",
    blocks.join("\n\n"),
    "",
  ].join("\n");

  writeFileSync(OUT_PATH, out);
  console.log(`wrote ${path.relative(process.cwd(), OUT_PATH)} (${blocks.length} types)`);
}

main();
