// AUTO-GENERATED by scripts/gen-types.mjs — DO NOT EDIT.
// Source of truth: apps/api/contexthub/models.py
//   1. cd apps/api && python scripts/export_schema.py
//   2. cd apps/desktop && npm run gen:types
// Property names are camelCase; lib/api/client.ts converts to/from the
// snake_case wire format at the HTTP boundary.

export const CONTRACT_VERSION = 2;

export interface Author {
  email: string;
  id: string;
  name: string;
}

export interface Citation {
  author?: string;
  score: number;
  sessionId: string;
  snippet: string;
  title: string;
  tool: string;
}

export interface IngestRequest {
  author: Author;
  category?: "engineering" | "sales" | "marketing" | "research" | "ops" | "other";
  redacted?: boolean;
  session: NormalizedSession;
  summary?: string;
  visibility?: "company" | "team" | "private";
}

export interface IngestResponse {
  blobUri: string;
  chunksIndexed: number;
  createdAt?: string;
  sessionId: string;
  skipped?: boolean;
  summaryUsed: boolean;
  updatedAt?: string;
}

export interface Message {
  id: string;
  model?: string;
  role: "user" | "assistant" | "system" | "tool";
  text: string;
  thinking?: string;
  timestamp?: string;
  toolName?: string;
}

export interface NormalizedSession {
  branchPointMessageId?: string;
  compactSummary?: string;
  compacted?: boolean;
  cwd?: string;
  endedAt?: string;
  filePath?: string;
  id: string;
  links?: Array<SessionLink>;
  messageCount?: number;
  messages?: Array<Message>;
  models?: Array<string>;
  parentSessionId?: string;
  preview?: string;
  project?: string;
  schemaVersion?: number;
  startedAt?: string;
  title: string;
  tokens?: TokenCounts;
  tool: "claude-code" | "codex" | "kilo-code";
}

export interface QueryFilters {
  author?: string;
  category?: "engineering" | "sales" | "marketing" | "research" | "ops" | "other";
  project?: string;
  tool?: "claude-code" | "codex" | "kilo-code";
}

export interface QueryRequest {
  filters?: QueryFilters;
  model?: string;
  provider?: string;
  question: string;
  topK?: number;
}

export interface QueryResponse {
  answer: string;
  citations: Array<Citation>;
}

export interface SessionCatalogRow {
  author?: string;
  blobUri: string;
  category: string;
  createdAt: string;
  id: string;
  messageCount: number;
  models?: Array<string>;
  preview?: string;
  project?: string;
  summary?: string;
  title: string;
  tokensInput?: number;
  tokensOutput?: number;
  tokensTotal?: number;
  tool: string;
  updatedAt?: string;
  visibility: string;
}

/** An external artifact linked to a session (PR, issue, doc, or another session). */
export interface SessionLink {
  kind: "pr" | "issue" | "doc" | "session";
  label?: string;
  url: string;
}

export interface StatsResponse {
  sessionsByCategory: Record<string, number>;
  sessionsByTool: Record<string, number>;
  totalChunks: number;
  totalSessions: number;
}

export interface SummarizeRequest {
  model?: string;
  provider?: string;
  session: NormalizedSession;
}

export interface SummarizeResponse {
  summary: string;
}

export interface TokenCounts {
  input?: number;
  output?: number;
}
