// AUTO-GENERATED by scripts/gen-types.mjs — DO NOT EDIT.
// Source of truth: apps/api/contexthub/models.py
//   1. cd apps/api && python scripts/export_schema.py
//   2. cd apps/desktop && npm run gen:types
// Property names are camelCase; lib/api/client.ts converts to/from the
// snake_case wire format at the HTTP boundary.

export const CONTRACT_VERSION = 2;

/** Response model for an uploaded or listed asset. */
export interface AssetMetadata {
  author: string;
  blobUri: string;
  category?: string;
  createdAt: string;
  description?: string;
  files?: Array<string>;
  id: string;
  kind: string;
  name: string;
  team?: string;
  version?: string;
  visibility?: string;
}

/** Paginated list of asset metadata rows. */
export interface AssetPage {
  items: Array<AssetMetadata>;
  limit: number;
  offset: number;
  total: number;
}

export interface Author {
  email: string;
  id: string;
  name: string;
  team?: string;
}

/** Request body for POST /v1/summarize/batch. */
export interface BatchSummarizeRequest {
  model?: string;
  provider?: "openai-batch" | "local" | "default";
  sessionIds: Array<string>;
}

/** Response for POST /v1/summarize/batch. */
export interface BatchSummarizeResponse {
  jobId: string;
  kind?: string;
  sessionCount: number;
}

export interface Citation {
  author?: string;
  score: number;
  sessionId: string;
  snippet: string;
  title: string;
  tool: string;
}

/** A directed relation between two graph nodes. */
export interface GraphEdge {
  dst: string;
  id: string;
  rel: string;
  sessionId?: string;
  src: string;
  weight?: number;
}

/** A knowledge-graph node (deduped by (kind, name)). */
export interface GraphNode {
  id: string;
  kind: string;
  name: string;
  sessionIds?: Array<string>;
  summary?: string;
  visibility?: string;
}

/** Response for GET /v1/graph and GET /v1/graph/session/{id}. */
export interface GraphResponse {
  edges: Array<GraphEdge>;
  nodes: Array<GraphNode>;
}

export interface IngestRequest {
  author: Author;
  category?: "engineering" | "sales" | "marketing" | "research" | "ops" | "other";
  redacted?: boolean;
  session: NormalizedSession;
  summary?: string;
  visibility?: "company" | "team" | "private";
}

export interface IngestResponse {
  blobUri: string;
  chunksIndexed: number;
  createdAt?: string;
  jobId?: string;
  sessionId: string;
  skipped?: boolean;
  summaryUsed: boolean;
  updatedAt?: string;
}

/** A background job record returned by GET /v1/jobs/{id} etc. */
export interface Job {
  createdAt: string;
  error?: string;
  finishedAt?: string;
  id: string;
  kind: string;
  payload?: Record<string, unknown>;
  result?: Record<string, unknown>;
  scheduledFor?: string;
  startedAt?: string;
  status: "queued" | "running" | "done" | "error";
}

export interface Message {
  id: string;
  model?: string;
  role: "user" | "assistant" | "system" | "tool";
  text: string;
  thinking?: string;
  timestamp?: string;
  toolName?: string;
}

export interface NormalizedSession {
  branchPointMessageId?: string;
  compactSummary?: string;
  compacted?: boolean;
  cwd?: string;
  endedAt?: string;
  filePath?: string;
  id: string;
  links?: Array<SessionLink>;
  messageCount?: number;
  messages?: Array<Message>;
  models?: Array<string>;
  parentSessionId?: string;
  preview?: string;
  project?: string;
  schemaVersion?: number;
  startedAt?: string;
  title: string;
  tokens?: TokenCounts;
  tool: "claude-code" | "codex" | "kilo-code";
}

export interface QueryFilters {
  author?: string;
  category?: "engineering" | "sales" | "marketing" | "research" | "ops" | "other";
  project?: string;
  tool?: "claude-code" | "codex" | "kilo-code";
}

export interface QueryRequest {
  filters?: QueryFilters;
  mode?: "hybrid" | "vector" | "keyword";
  model?: string;
  provider?: string;
  question: string;
  topK?: number;
  useGraph?: boolean;
}

export interface QueryResponse {
  answer: string;
  citations: Array<Citation>;
}

/** A single extracted rule/preference. */
export interface Rule {
  author?: string;
  createdAt: string;
  evidence?: Array<string>;
  id: string;
  rationale?: string;
  scope?: string;
  status?: "proposed" | "accepted" | "rejected";
  text: string;
  updatedAt?: string;
}

/** Paginated list of rules. */
export interface RulePage {
  items: Array<Rule>;
  limit: number;
  offset: number;
  total: number;
}

export interface SessionCatalogRow {
  author?: string;
  blobUri: string;
  category: string;
  createdAt: string;
  id: string;
  messageCount: number;
  models?: Array<string>;
  preview?: string;
  project?: string;
  summary?: string;
  team?: string;
  title: string;
  tokensInput?: number;
  tokensOutput?: number;
  tokensTotal?: number;
  tool: string;
  updatedAt?: string;
  visibility: string;
}

/** Full detail response for a single session (catalog row + raw blob). */
export interface SessionDetail {
  catalog: SessionCatalogRow;
  raw?: Record<string, unknown>;
}

/** An external artifact linked to a session (PR, issue, doc, or another session). */
export interface SessionLink {
  kind: "pr" | "issue" | "doc" | "session";
  label?: string;
  url: string;
}

/** Paginated list of catalog rows. */
export interface SessionPage {
  items: Array<SessionCatalogRow>;
  limit: number;
  offset: number;
  total: number;
}

export interface StatsResponse {
  sessionsByCategory: Record<string, number>;
  sessionsByTool: Record<string, number>;
  totalChunks: number;
  totalSessions: number;
}

export interface SummarizeRequest {
  model?: string;
  provider?: string;
  session: NormalizedSession;
}

export interface SummarizeResponse {
  summary: string;
}

export interface TokenCounts {
  input?: number;
  output?: number;
}
