/**
 * Rules extraction types + pure helpers (Task 14).
 *
 * Mirrors the API's Rule/RulePage models (GET /v1/rules); the ApiClient
 * camelCases the wire format (created_at → createdAt). Rules are mined from
 * the author's recent sessions by the hub's `rules_extract` job and stay in
 * "proposed" status until the user explicitly accepts them — only accepted
 * rules are ever exported (consent gate).
 */

// ─── types ───────────────────────────────────────────────────────────────────

export type RuleStatus = "proposed" | "accepted" | "rejected";

export interface Rule {
  id: string;
  text: string;
  rationale?: string | null;
  /** Session ids that evidence this rule. */
  evidence: string[];
  scope?: string | null;
  status: RuleStatus;
  author?: string | null;
  createdAt: string;
  updatedAt?: string | null;
}

export interface RulePage {
  items: Rule[];
  total: number;
  limit: number;
  offset: number;
}

// ─── helpers ─────────────────────────────────────────────────────────────────

export interface GroupedRules {
  proposed: Rule[];
  accepted: Rule[];
  rejected: Rule[];
}

/** Bucket rules by status; each bucket sorted newest-first by createdAt. */
export function groupRulesByStatus(rules: Rule[]): GroupedRules {
  const groups: GroupedRules = { proposed: [], accepted: [], rejected: [] };
  for (const r of rules) {
    (groups[r.status] ?? groups.proposed).push(r);
  }
  const newestFirst = (a: Rule, b: Rule) => b.createdAt.localeCompare(a.createdAt);
  groups.proposed.sort(newestFirst);
  groups.accepted.sort(newestFirst);
  groups.rejected.sort(newestFirst);
  return groups;
}

/**
 * Render accepted rules as a CLAUDE.md-style markdown block.
 *
 * Mirrors the server's GET /v1/rules/export format so the "Copy as CLAUDE.md"
 * button produces identical output without a round-trip. Non-accepted rules
 * are filtered out — consent is explicit.
 */
export function rulesToMarkdown(rules: Rule[]): string {
  const accepted = rules.filter((r) => r.status === "accepted");

  if (accepted.length === 0) {
    return "# Rules\n\n_No accepted rules yet. Accept proposed rules first._\n";
  }

  const lines: string[] = [
    "# Rules",
    "",
    "> Generated by Context Hub — accepted rules only.",
    "",
  ];
  for (const r of accepted) {
    lines.push(`- ${r.text}`);
    if (r.rationale) {
      lines.push(`  _${r.rationale}_`);
    }
  }
  lines.push("");
  return lines.join("\n");
}
